name: nikolajovic
description: Nikola Jović Curriculum Vitae
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flex_color_scheme: ^7.3.1
  flutter_bloc: ^8.1.6
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  screenshot: ^3.0.0
  pdf: ^3.11.0
  image: ^4.2.0
  universal_html: ^2.2.4
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
